### PR TITLE
docs: various improvements

### PR DESCRIPTION
**Pull request by vthiery**
* notification_rule doc was refering to `filter` block instead of `criteria`
* emphasize possible and default values
* remove trailing whitespaces
* make import examples slightly clearer

### CODE REVIEW

**Review by multani — DISMISSED** [review]
Looks much better indeed :+1:

**Review by prakhar-mudaiya — DISMISSED** [review]
LGTM. Please rebase the changes

**Review by prakhar-mudaiya — COMMENTED** [review]
Once rebased. We can merge it

**Comment by vthiery** [comment]
Hi @prakhar-mudaiya ! Thanks for the quick review. I have rebased my PR.

**Review by prakhar-mudaiya — APPROVED** [review]

**Pull request merged**
