### PR TITLE
New resource - opsgenie_notification_policy

### PR DESCRIPTION
**Pull request by jaceq**
I added notification policy resource. 
Tests are included.
Documentation is included.

I also included this fix: https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/28 (as otherwise it didn't work).

### CODE REVIEW

**Comment by jaceq** [comment]
And it seems this partially resolves: https://github.com/terraform-providers/terraform-provider-opsgenie/issues/63

**Review by ffahri — COMMENTED** [review]
Thank you for creating this pull request. I will make e2e tests and reviews asap.

**Comment by ffahri** [comment]
e2e test are good
lgtm

**Comment by ffahri** [comment]
i will opsgenie/opsgenie-go-sdk-v2#28 make this merged after that i want you to update your pr to latest go-sdk-version @jaceq

**Comment by jaceq** [comment]
@ffahri 
Could you also merge: https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/30
and https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/31 ?

**Comment by ffahri** [comment]
@jaceq we merged sdk prs and released new version could you please update your pull requests

**Comment by jaceq** [comment]
@ffahri I updated this one as you asked.

**Review by ffahri — APPROVED** [review]
thanks for these changes

**Pull request merged**
