### PR TITLE
Add options to customize the API backoff mechanism

### PR DESCRIPTION
**Pull request by iuriaranda**
This makes the backoff mechanism customizable via the following new options in the provider configuration:

api_retry_count
api_retry_wait_min
api_retry_wait_max

As per https://github.com/opsgenie/terraform-provider-opsgenie/issues/268

### CODE REVIEW

**Review by duboisph — DISMISSED** [review]
Lgtm, but I guess that's for the maintainers to decide 🙂

**Comment by iuriaranda** [comment]
hey @koushik-swaminathan , any chance you could give a look at this PR? :pray: 

We've been using our fork (this PR) to overcome Opsgenie's rate-limiting for more than a year now, and it's been working good. I think it would be very helpful for users to have the ability to configure the back-off mechanism in the official provider, specially considering that #268 was closed unresolved.

Let me know if there's anything I still need to take care of to be able to merge the PR.

Thanks!

**Comment by koushik-swaminathan** [comment]
Hi @iuriaranda, I will merge it today :)

**Review by koushik-swaminathan — APPROVED** [review]
LGTM

**Comment by duboisph** [comment]
Hi @koushik-swaminathan! Do you have an idea when this could be released?

**Pull request merged**
