### PR TITLE
Fix drift for empty time_restriction

### LINKED ISSUE #412: Time restriction drift
### Terraform Version
```
❯ terraform version         
Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.19.0
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.34
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opsgenie_team_routing_rule (possibly anything else using `time_retriction`)

### Terraform Configuration Files
```hcl
     resource "opsgenie_team_routing_rule" "test" {
        name       = "test" 
        order      = 0
        team_id    = "xxx"
        timezone   = "America/Los_Angeles"

        criteria {
            type = "match-all"
        }

        notify {
            type = "none"
        }
      }
```

### Expected Behavior
No drift once applied

### Actual Behavior
Perpetual drift on `opsgenie_team_routing_rule` without a `time_restriction`. E.g.

```
  ~ resource "opsgenie_team_routing_rule" "test" {
        name       = "test"
        # (4 unchanged attributes hidden)

      - time_restriction {
          - restriction {
              - end_hour   = 0 -> null
              - end_min    = 0 -> null
              - start_hour = 0 -> null
              - start_min  = 0 -> null
            }
        }

        # (2 unchanged blocks hidden)
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
1. `terraform plan`. This step will show a drift

### References
- I believe issue was introduced in #404 around https://github.com/opsgenie/terraform-provider-opsgenie/blob/master/opsgenie/util.go#L120C11-L137. When there is no time restriction, this block adds a `restriction` with default value leading to the drift. I think it should have returned an empty map instead.

### PR DESCRIPTION
**Pull request by gjacquet**
Fix drift when time_restriction block is not defined.

Fixes #412.

### CODE REVIEW

**Comment by axdotl** [comment]
Highly appreciate this pull request 🙏🏼 
Maybe @koushik-swaminathan can support here to get this merged.

**Comment by koushik-swaminathan** [comment]
LGTM, thank you @gjacquet

**Review by koushik-swaminathan — APPROVED** [review]

**Comment by axdotl** [comment]
Thanks @koushik-swaminathan for the review.

Is there something missing to get this merged?

**Comment by koushik-swaminathan** [comment]
Hi @axdotl, I will be merging it today :)

**Comment by PierreBart** [comment]
Hello @koushik-swaminathan, when are you planning the next release to include this fix ?

**Comment by avivek** [comment]
Hi @koushik-swaminathan,
When is the next release expected??
We are awaiting this fix.

**Pull request merged**
