### PR TITLE
Notification rule resource added

### PR DESCRIPTION
**Pull request by jaceq**
Hi,

I am trying again (refering this this: https://github.com/terraform-providers/terraform-provider-opsgenie/issues/76 and https://github.com/terraform-providers/terraform-provider-opsgenie/pull/68)

I tested what I could but I cannot do e2e tests due to no test account.
If there are e2e test errors could you @ffahri provide debug output to see which operation exactly fails?

### CODE REVIEW

**Comment by ffahri** [comment]
```
=== RUN   TestAccOpsGenieNotificationRule_basic
--- FAIL: TestAccOpsGenieNotificationRule_basic (2.61s)
testing.go:569: Step 0 error: errors during apply:
Error: Error occurred with Status code: 422, Message: Request body is not processable. Please check the errors., Took: 0.026000, RequestId: a1393e81-89a1-4308-be96-4047988bdc34, Error Detail: map[contact :does not exist]
(source code not available)
FAIL
```

**Comment by jaceq** [comment]
@ffahri I've made correction, please re-try and let me know if this is ok now.

**Comment by ffahri** [comment]
The e2e tests are green. I will test this branch manually for some edge cases and let you know thanks @jaceq

**Comment by ffahri** [comment]
Sorry for late response @jaceq 
I tested locally everything seems OK. 
However, when we introduced other fields people who use this version need to re-apply their configurations and this may cause some problems (such as default variables- if they set something and upgrade their provider their rule will change).

I think we can add other fields as well then release this resource fully. I checked our provider and it seems easy because we already have those resources inside codebase.
I'm holding this pr to not to block master. But after these updates, I will merge. I can also contribute your pr if you are okay with that?

**Comment by jaceq** [comment]
Hi @ffahri ,

I am not sure I understand to be honest.
You mean, there are new fields etc merged within last 14 days? 
or do you mean there are changes to opsgenie-go-sdk ?

This PR doesn't touch other resources, I am a bit confused.
My worry is, that if we shelf it, this realistically will not get added as PR will get outdated before rest of fields is added.

btw. quite some time I sent you message on twitter, not sure if you've seen it ;)

**Comment by ffahri** [comment]
What I am saying is we did not introduce non-mandatory some fields in this PR. This means people need to modify this manually. When we introduce these fields (assuming some options are default) can cause some trouble when applying the new version. By the holding the PR I mean if something urgent needs to be merged this resource will also go to customers 😄

**Comment by jaceq** [comment]
Ah, yes, that is right. As I explained in original PR, given I did that for my work needs and was able to spend only as much work time as I had to I did a basic set of attributes that allowed us to use it.
I do get your argument, however I honestly think it's better to have something than nothing, also adding additional attributes to an existing resource is easier.
Anyway, it is your call obviously, I internally use this resource from the beginning - just wanted to share with community.

**Review by ffahri — APPROVED** [review]

**Comment by ffahri** [comment]
will track this in #121 all fields implemented with preserving this commits

**Pull request closed without merging**
