### PR TITLE
Add link to full list of integration types.

### PR DESCRIPTION
**Pull request by kenske**
It took me a while to find out where I could get the names of integrations. This should be part of the docs.

### CODE REVIEW

**Comment by ffahri** [comment]
Hey this link is not solves this problem. I guess we need to add integration naming map to docs site.

**Comment by kenske** [comment]
I'd say this is better than nothing, or waiting until the docs are updated.

**Comment by ffahri** [comment]
Yes there will be a document coming for this probably this week for Integration and name mapping.

**Comment by ffahri** [comment]
Hey @kenske document is published. 
https://docs.opsgenie.com/docs/integration-types-to-use-with-api
could you please update your pull request

**Comment by kenske** [comment]
Done

**Review by ffahri — APPROVED** [review]

**Comment by ffahri** [comment]
Thanks for the contribition

**Pull request merged**
