### PR TITLE
Alert Policy: Change alert_description to description

### LINKED ISSUE #202: Cannot set description for opsgenie_alert_policy
### Terraform Version
v0.13.5

### Affected Resource(s)
- opsgenie_alert_policy

### Terraform Configuration Files
```hcl
resource "opsgenie_team" "test" {
  name                = "test"
}
resource "opsgenie_alert_policy" "test" {
  name                = "test"
  message             = "test message"
  team_id             = opsgenie_team.test.id
  alert_description   = "test description"
}
```

### Expected Behavior
Alert policy is created with Alert description.
Repeated `terraform apply` should not detect any changes.

### Actual Behavior
Alert policy alert description (under "Show advanced fields") sets Description to `{{description}}`
image

Repeated execution shows the same intended change as executing the first time:
image

Setting Description field manually prior to running terraform is also overwritten to `{{description}}` after `terraform apply`

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`

### PR DESCRIPTION
**Pull request by promaty**
Fixes #202

### CODE REVIEW

**Comment by franeksaww** [comment]
Hi! @promaty when this fix can be merged?

**Comment by promaty** [comment]
@franeksaww, Someone with repo access has to review and merge it, @ffahri perhaps?

**Comment by Lucas-C** [comment]
I think this PR is out-of-date with the `master` branch now.

I'd love to see this merged & released too!

**Comment by ffahri** [comment]
Hey updated go-sdk-v2 first waiting the release
https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/93
after that i'll update here

**Pull request closed without merging**
