### PR TITLE
Fix notification policy filters ordering

### PR DESCRIPTION
**Pull request by gjacquet**
This should address #409.

Conditions and restrictions should be Sets rather than Lists.

### CODE REVIEW

**Comment by gjacquet** [comment]
This is basically the same fix as #390

**Comment by koushik-swaminathan** [comment]
@gjacquet could you refer [#390](https://github.com/opsgenie/terraform-provider-opsgenie/pull/390) and make similar changes throughout the file?

**Comment by gjacquet** [comment]
@koushik-swaminathan This is what I did but I missed a few spots that I addressed this morning.
I ran a few test on my project and it seems to address my issue.

**Comment by koushik-swaminathan** [comment]
@gjacquet alright let me test it out and get back to you

**Comment by Baarsgaard** [comment]
Hi @gjacquet , just an FYI.
When you commit a binary and delete it in a subsequent commit, the binary is still stored in the repository.
You would need to rebase and squash your commits together to properly delete the binary from the initial commit that introduced it.

**Comment by gjacquet** [comment]
@Baarsgaard Done!
I guess I am more used to the Github squash and merge feature that does all of this as the PR is getting merged.

**Comment by koushik-swaminathan** [comment]
Hi @gjacquet, another PR has already included these changes along with a few others so I'll be merging that instead. Thank you!

**Comment by gjacquet** [comment]
@koushik-swaminathan sounds good!
Out of curiosity, could you please send the link to the other PR addressing this issue? It seems to be #404, is it correct? Do you have an ETA on the next provider release?

**Comment by Baarsgaard** [comment]
#404 and I think it's released already! https://registry.terraform.io/providers/opsgenie/opsgenie/0.6.34

**Pull request closed without merging**
