### PR TITLE
remove user from teams on delete

### LINKED ISSUE #184: Opsgenie user removal wrong order
Hi there,

I've got some issue when trying to remove a user from an opsgenie_user resource when this user is also referenced as a team member or a participant to a schedule rotation

### Terraform Version
Terraform v0.12.29
+ provider.opsgenie v0.5.0

### Affected Resource(s)
- opsgenie_user
- opsgenie_schedule_rotation
- opsgenie_team

### Debug Output
```
  # opsgenie_team.teams["teamtest"] will be updated in-place
  ~ resource "opsgenie_team" "teams" {
        delete_default_resources = true
        description              = "Testing intgerations and stuff"
        id                       = "589b1cf3-8e6c-431d-80a5-a02951f2a45c"
        name                     = "teamtest"

        member {
            id   = "551eae0c-9c3f-4adb-afee-e3998fe6dd42"
            role = "admin"
        }
      ~ member {
          ~ id   = "6551164a-6344-48ee-a68e-6a0d9012d1cb" -> "4a3e014a-9fc6-4104-baa1-d303d5a4cb92"
            role = "user"
        }
      - member {
          - id   = "4a3e014a-9fc6-4104-baa1-d303d5a4cb92" -> null
          - role = "user" -> null
        }
    }

  # opsgenie_user.users["usertest"] will be destroyed
  - resource "opsgenie_user" "users" {
      - full_name = "User Test" -> null
      - id        = "6551164a-6344-48ee-a68e-6a0d9012d1cb" -> null
      - locale    = "fr_CH" -> null
      - role      = "Admin" -> null
      - timezone  = "Europe/Belgrade" -> null
      - username  = "user.test@example.com" -> null
    }

Plan: 0 to add, 10 to change, 1 to destroy.

Do you want to perform these actions in workspace "staging"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opsgenie_user.users["user.test@example.com"]: Destroying... [id=6551164a-6344-48ee-a68e-6a0d9012d1cb]

Error: Error occurred with Status code: 428, Message: User cannot be modified. Please remove it from teams: [teamtest], Took: 0.040000, RequestId: 6f3a73f1-19d2-488d-9559-4ec423ab5713
```

### Expected Behavior
Terraform should remove the user from the team(s) and the schedule rotation(s) and then remove the user

### Actual Behavior
An error occurs mentioning that the user is still part of team(s) and/or schedule rotation(s)

### Steps to Reproduce
1. Create a user with
2. Create a team and attach the user to it as a member
3. Remove the user from the tf file and remove the member in the team tf file

### PR DESCRIPTION
**Pull request by ceriath**
This fixes #184 by simply removing the user from all their teams when deleting the user.

### CODE REVIEW

**Comment by frknyldz** [comment]
Hi @ceriath, thank you very much for your collaboration but since there is a [solution](https://github.com/opsgenie/terraform-provider-opsgenie/issues/184#issuecomment-1275741248) for that issue we've closed it. The Opsgenie behavior and response are correct actually. It's an ordering and dependency problem caused by the Terraform.

**Comment by zonArt** [comment]
Sorry but as mentioned the solution is NOT a solution, managing the order within the terraform provider is much more convenient. Also the process of removal of user is mostly (as per what terraform can offer) an automated process, needing to do that in two steps takes it back to do it manually which removes all the interest of automation. Please consider doing something so automation and managing users as code can be done the way it should

**Comment by fnuva** [comment]
Hi all, any users  that already have dependency on schedule, escalation, team or other resources can not be removed easily. Please correct me if I am wrong but your PR will remove the relation of user with teams even if it is still in terraform configuration. 
Even if it solves your problem, it can not solve the problem that remove the user but keep the relation of user with teams.  
Please consider the terraform configuration that keep the user email inside the team but you removed the user completely. 
According to your PR, the first deployment will remove user everywhere and second deployment will fail because there is no user to add the team.  To sum up, if we break the idempotency in between modules, it will cause another problem even if it is solved. 
Unfortunately, there are no option to keep the order in between modules in the plugin. However, we have created the internal ticket and find out the better solution to solve it.

**Comment by frknyldz** [comment]
Hi @ceriath, could you please check the [latest](https://github.com/opsgenie/terraform-provider-opsgenie/releases/tag/v0.6.16) version to confirm? Your commit was merged also. Thanks for your contribution.

**Comment by ceriath** [comment]
@frknyldz That works. Thank you!

**Pull request closed without merging**
