### PR TITLE
Fix changing the owner team of an API integration

### LINKED ISSUE #145: Update owner team in API integration
Changing the "owner team" on an API integration produces a plan that shows the team is going to be updated, but the apply never updates the team.

### Terraform Version

```
$ terraform version
Terraform v0.12.29
```

and `terraform-providers/opsgenie: 0.4.1`

### Affected Resource(s)

Please list the resources as a list, for example:

- `opsgenie_api_integration`
- maybe others?

### Terraform Configuration Files

Changing:

```hcl
resource opsgenie_api_integration "api1" {
  name = "RDS"
  type = "AmazonRds"

  owner_team_id = opsgenie_team.team_abc.id
}
```

```hcl
resource opsgenie_api_integration "api1" {
  name = "RDS"
  type = "AmazonRds"

  owner_team_id = opsgenie_team.team_123456.id
}
```

Produces a plan like:

```
  # opsgenie_api_integration.api1 will be updated in-place
  ~ resource "opsgenie_api_integration" "api1" {
        allow_write_access     = true
        enabled                = true
        id                     = "6be305fb-27ec-47b5-b845-acef0e92ec9c"
        name                   = "RDS"
      ~ owner_team_id          = "54f2842a-a055-44aa-bea7-9cd533b836b5" -> "10ff85dc-9d1b-4e3c-a23e-d4ea6b2f7487"
        suppress_notifications = false
        type                   = "AmazonRds"
    }
```

### Expected Behavior

The owner team should be `team_123456` instead of `team_abc`. Subsequent plans should show no changes.

### Actual Behavior

* The owner team stays `team_abc`.
* Subsequent plans always show the the owner team would be changed.

### PR DESCRIPTION
**Pull request by multani**
This is not supported by the API: https://docs.opsgenie.com/docs/integration-api#update-integration

Note that, if changed, this will recreate the API integration from
scratch and will most likely change the API key associated with the
integration: if it has been already installed somewhere, the integration
will stop working until it has been updated where it has been installed.

Fix: #145

### CODE REVIEW

**Comment by multani** [comment]
@ffahri Any news on this?

I understand that recreating a brand new integration is not ideal, but were you able to raise this issue to the OpsGenie Development team to see if they could extend their API to support this type of use-case?

**Review by kamilhristov — APPROVED** [review]

**Comment by kamilhristov** [comment]
@fnuva Please provide some input on this 🙏

Hitting the same problem and prefer re-creating the resource instead of silently ignoring the change.

**Comment by plaes** [comment]
It would be nice it it provides a warning message that would at least detect the drift (it seems that currently the existing state is not compared with state from OpsGenie) and suggest the user to either:
a) fixing it manually in the OpsGenie UI (so you can continue using existing keys)...
b) ...or suggest recreating the integration (which would blow up existing key)

We just ran into this after reassigning some of the keys without existing team and thus missed critical alerts.

**Comment by PrayagS** [comment]
Any updates on this? Seems like we might just have to run a fork if this isn't going anywhere. Thanks.

**Comment by Kerwood** [comment]
> Any updates on this? Seems like we might just have to run a fork if this isn't going anywhere. Thanks.

Hmm, I wish that Atlassian/Opsgenie would put more working resources into their Terraform provider, which is obviously used by many of their customers.

This small PR shouldn't have gone unnoticed for two years.

**Comment by mlessig** [comment]
We are also having this issue.

**Review by koushik-swaminathan — APPROVED** [review]
@multani, i have reviewed and tested your changes, the PR doesn't break anything and changes the owner teams and responders succesfully.

**Pull request merged**
