### PR TITLE
service_incident_rules: Conditions is a set not an ordered list.

### LINKED ISSUE #332: opsgenie_service_incident_rule conditions order is not stable causing "in-place"  updates though nothing changes
I have following resources:

```
resource "opsgenie_service_incident_rule" "pingdom" {
  for_each   = toset(["service1", "service2", "service3"]
  service_id = resource.opsgenie_service.service[each.value].id

  incident_rule {
    condition_match_type = "match-all-conditions"
    conditions {
      field          = "source"
      not            = false
      operation      = "equals"
      expected_value = "Pingdom"
    }
    conditions {
      field          = "description"
      not            = false
      operation      = "matches"
      expected_value = ".*Check Name : ${var.site}/${each.value}:.*"
    }
    conditions {
      field          = "tags"
      not            = true
      operation      = "contains"
      expected_value = "no-incident"
    }
    ...
```

After running apply and then apply/plan again, some of the conditions have changed order, which is causing in-place updates (though nothing has changed):
```
  ~ resource "opsgenie_service_incident_rule" "pingdom" {
        id         = "..."
        # (1 unchanged attribute hidden)

      ~ incident_rule {
            # (1 unchanged attribute hidden)

          ~ conditions {
              ~ expected_value = ".*Check Name : test-env/service1:.*" -> "Pingdom"
              ~ field          = "description" -> "source"
              ~ operation      = "matches" -> "equals"
                # (1 unchanged attribute hidden)
            }
          ~ conditions {
              ~ expected_value = "Pingdom" -> ".*Check Name : test-env/service1:.*"
              ~ field          = "source" -> "description"
              ~ operation      = "equals" -> "matches"
                # (1 unchanged attribute hidden)
            }

            # (2 unchanged blocks hidden)
        }
    }
```

### Terraform Version
```
Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.14
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opsgenie_service_incident_rule

### PR DESCRIPTION
**Pull request by plaes**
Should fix #332

### CODE REVIEW

**Comment by plaes** [comment]
Hey @frknyldz, @fnuva!
Could you please review this one? (We have been running these changes in production for more than a month now..)

**Comment by plaes** [comment]
Ping @frknyldz @fnuva!
Could you please review/apply this?

**Review by frknyldz — APPROVED** [review]
LGTM!

**Comment by frknyldz** [comment]
Hi @plaes, we've tested these changes and verified it doesn't break any functionality and solves issue #332. Thanks for your contribution.

**Review by havardsi — COMMENTED** [review]
+1

**Pull request merged**
