### PR TITLE
Added resource notification_rule

### LINKED ISSUE #48: Opsgenie provider can' t configure Notification Rules
Hello,

I'm afraid that Terraform Opsgenie provider cannot enable user to modify notification rules.
It looks you can only configure the user contacts and that is it.

https://www.terraform.io/docs/providers/opsgenie/r/user_contact.html

Thanks

### PR DESCRIPTION
**Pull request by jaceq**
As per title. I added new resource 'notification_rule'
This enables users to manage user notification.

INFO:
I have NOT implemented all attributes, please refer to documentation to see what is there.
All required fields are in as well as steps, so enough for basic usage.

This partially resolves https://github.com/terraform-providers/terraform-provider-opsgenie/issues/48

This includes SDK fixes:
https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/30
https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/31

### CODE REVIEW

**Comment by ffahri** [comment]
@jaceq could you please update this pr as well

**Comment by jaceq** [comment]
@ffahri Updated as requested.

**Comment by jaceq** [comment]
Any news @ffahri  ?

**Comment by ffahri** [comment]
Thank you i think we should add other fields as well. I will push the branch if thats okey for you ? 
@jaceq

**Comment by jaceq** [comment]
Hi @ffahri sure, go ahead.

**Comment by ffahri** [comment]
Hey i will make e2e test asap and merge your pr. I think introduce other fields later will much better than hold this.

**Review by ffahri — APPROVED** [review]

**Review by ffahri — APPROVED** [review]

**Comment by ffahri** [comment]
@jaceq hey e2e test does not pass 
```
 [31mERRO [0m[2020-03-06T12:28:06.156100018Z] Error occurred with Status code: 422, Message: Request body is not processable. Please check the errors., Took: 0.027000, RequestId: 773d98a5-40a1-4bc1-8a8b-385e4e08de40, Error Detail: map[contact :does not exist] 
```
Do you have time to fix this issue we can revert and re intrduce later ?

**Pull request merged**
